customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

  - key: "R"
    command: "git checkout HEAD -- {{.SelectedFile.Name | quote}}"
    description: "restore file"
    context: "files"
    loadingText: "restore file"
    subprocess: true

  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true

  - key: "<c-g>"
    command: "gh pr create"
    context: "global"
    loadingText: "Creating pull request on GitHub"
    subprocess: true

  - key: "E"
    prompts:
      - type: "input"
        title: "Add empty commit"
        initialValue: "fix: "
    command: 'git commit --allow-empty -m "{{index .PromptResponses 0}}"'
    context: "global"
    subprocess: true

