customCommands:
  - key: "C"
    command: "git cz c"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true

  - key: "R"
    command: "git checkout HEAD -- {{.SelectedFile.Name | quote}}"
    description: "restore file"
    context: "files"
    loadingText: "restore file"
    subprocess: true

  - key: "W"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "global"
    subprocess: true

  - key: "<c-g>"
    command: "gh pr create"
    context: "global"
    loadingText: "Creating pull request on GitHub"
    subprocess: true

  - key: "E"
    prompts:
      - type: "input"
        title: "Add empty commit"
        initialValue: "fix: "
    command: 'git commit --allow-empty -m "{{index .PromptResponses 0}}"'
    context: "global"
    subprocess: true
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff966c"
      - "bold"
    inactiveBorderColor:
      - "#589ed7"
    searchingActiveBorderColor:
      - "#ff966c"
      - "bold"
    optionsTextColor:
      - "#82aaff"
    selectedLineBgColor:
      - "#2d3f76"
    cherryPickedCommitFgColor:
      - "#82aaff"
    cherryPickedCommitBgColor:
      - "#c099ff"
    markedBaseCommitFgColor:
      - "#82aaff"
    markedBaseCommitBgColor:
      - "#ffc777"
    unstagedChangesColor:
      - "#c53b53"
    defaultFgColor:
      - "#c8d3f5"
keybinding:
  commits:
    moveDownCommit: <c-4>
    moveUpCommit: <c-5>
