#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
  selected=$1
else
  explicit_dirs=(
    "$HOME"
    "$HOME/dev"
    "$HOME/Downloads/"
  )

  repos=$(find ~/dev -mindepth 1 -maxdepth 3 \( -type d -o -type l \))
  vaults=$(find ~/vaults -mindepth 1 -maxdepth 1 -type d)
  utils=$(find ~/utils -mindepth 1 -maxdepth 1 -type d)

  all_dirs=("${explicit_dirs[@]}" "$repos" "$vaults" "$utils")

  selected=$(printf '%s\n' "${all_dirs[@]}" | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
  tmux new-session -ds "$selected_name" -c "$selected"
  tmux send-keys -t "$selected_name" "dev" Enter
  tmux set-hook -t "$selected_name" after-split-window "send-keys 'dev' Enter"
fi

tmux switch-client -t "$selected_name"
