#!/usr/bin/env bash

todo_dir=~/repo/dotfiles/_personal

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s todo -c $todo_dir
    tmux send-keys -t todo "nvim $todo_dir/todo.md"
    exit 0
fi

if ! tmux has-session -t=todo 2> /dev/null; then
    tmux new-session -ds todo -c $todo_dir
fi

tmux switch-client -t todo
